export default {
    1: '',
    2: 'Proper Restaurant Temperature',
    3: 'Proper Hazardous Food Storage',
    4: '',
    5: '',
    6: 'Use of Gloves in Food Prep',
    7: '',
    8: 'Sanitizing Rinse for Equipment / Utensils',
    9: '',
    10: 'Correct Sewage & Water Waste Disposal',
    11: 'Adequate Number of Sinks',
    12: 'Sinks Convenient to Food Prep Area',
    13: 'No Insects, Rodents, or Animals',
    14: 'Previous Serious Violation Corrected',
    15: '',
    16: 'Food Protected During Storage',
    17: '',
    18: 'Adequate Insect / Rodent - Proofing',
    19: 'Outside Garbage Area',
    20: '',
    21: 'Certified Food Manager On Site',
    22: '',
    23: '',
    24: '',
    25: '',
    26: '',
    27: 'Bathrooms Clean and Sanitary',
    28: '',
    29: 'Previous Violations Corrected',
    30: 'Food Containers Well-Maintained',
    31: 'Food Utensils Properly Cleaned / Disposed',
    32: 'Food Prep Area Well-Maintained',
    33: 'Food Equipment Sanitized',
    34: 'Floors Well-Maintained/Constructed',
    35: 'Walls & Ceilings Well-Maintained/Constructed',
    36: 'Lighting Adequate',
    37: 'Restroom Privacy and Separation',
    38: 'Rooms Well-Ventilated / Plumbing Maintained',
    39: 'Linen Properly Cleaned / Stored',
    40: 'Refrigeration Thermometers Provided / Visible',
    41: 'General Tidiness',
    42: 'Hygenic Preparation of Food',
    70: 'Smoking Regulations'
}